### ISSUE TITLE
Fix spelling errors in manpage

### ISSUE THREAD

**Issue by carnil** [shlomif/perl-Statistics-Descriptive#2]
Hi,

In Debian we are currently applying the following patch to
Statistics-Descriptive.
We thought you might be interested in it too.

    Description: Fix spelling errors in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2018-07-12
    Bug: 
    

The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libstatistics-descriptive-perl/raw/master/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by shlomif** [comment]
Hi!

Thanks for the report but my git-fu of applying this patch with attribution is failing me - "git am" fails. A DDG search is not helpful. Can you give me instructions?

**Comment by carnil** [comment]
@shlomif I created a new pull request by tweaking the patch. It is at https://github.com/shlomif/perl-Statistics-Descriptive/pull/3 .

The problem arises apparently on our end since the perl-Statistics-Descriptive is a bit "not-standard", the in the toplevel there i not the module, but only following in the subdirectory Statistics-Descriptive are the actual module.

**Comment by shlomif** [comment]
@carnil : thanks!

**Comment by shlomif** [comment]
@carnil : merged, thanks!
