### ISSUE TITLE
Gibberish sentence in manual

### ISSUE THREAD

**Issue by melak** [shlomif/perl-Statistics-Descriptive#5]
https://github.com/shlomif/perl-Statistics-Descriptive/blob/46596fd19d67e49d0aadf77255ba8da0c74f701b/Statistics-Descriptive/lib/Statistics/Descriptive.pm#L424-426

This should probably read

`Note that unless the set of bins contain the entire range, the sum of counts returned will be less than the sample size.`

**Comment by melak** [comment]
Excellent, cheers!

**Comment by shlomif** [comment]
On Fri, 26 Oct 2018 02:21:57 -0700
melak <notifications@github.com> wrote:

> Excellent, cheers!
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
First stop for Perl beginners - http://perl-begin.org/

Ten measures of slowness went down to the world.  Windows Update required at
least eleven, so more had to be provided.
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
